-- TEMPORARY: Disable RLS for development testing
-- Remove this migration before production!

-- Disable RLS on all tables for dev testing
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE group_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE pacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE pact_participants DISABLE ROW LEVEL SECURITY;
ALTER TABLE check_ins DISABLE ROW LEVEL SECURITY;
ALTER TABLE roast_threads DISABLE ROW LEVEL SECURITY;
ALTER TABLE roast_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE reactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_recaps DISABLE ROW LEVEL SECURITY;
